2018-05-23 11:03:36 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: ARGUS)
2018-05-23 11:03:36 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.7, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 17.5.0 (OpenSSL 1.0.2n  7 Dec 2017), cryptography 2.1.4, Platform Windows-7-6.1.7601-SP1
2018-05-23 11:03:36 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'ARGUS', 'CONCURRENT_ITEMS': 200, 'CONCURRENT_REQUESTS': 100, 'COOKIES_ENABLED': False, 'DOWNLOAD_MAXSIZE': 10000000, 'FEED_URI': 'file:///I:/%21Projekte/BMBF_TOBI_131308/01_Arbeitspakete/01_Webscraper/Webscraper/crawler/ARGUS/items/ARGUS/textspider/2a7035525e6811e8892f5459596fa410.jl', 'LOG_FILE': 'logs\\ARGUS\\textspider\\2a7035525e6811e8892f5459596fa410.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'ARGUS.spiders', 'REACTOR_THREADPOOL_MAXSIZE': 30, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['ARGUS.spiders']}
2018-05-23 11:03:36 [py.warnings] WARNING: c:\programdata\anaconda3\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.feedexport.FeedExporter` class is deprecated, use `scrapy.extensions.feedexport.FeedExporter` instead
  ScrapyDeprecationWarning)

2018-05-23 11:03:36 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-05-23 11:03:36 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-05-23 11:03:36 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-05-23 11:03:36 [scrapy.middleware] INFO: Enabled item pipelines:
['ARGUS.pipelines.TextPipeline']
2018-05-23 11:03:36 [scrapy.core.engine] INFO: Spider opened
2018-05-23 11:03:36 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-23 11:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET http://knorr-bremseandhaldex.com  sowie der website> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 170, in errorback
    loader.add_value("start_url", "")
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET http://autoservice-auerbach.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 150, in errorback
    loader.add_value("start_url", "")
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://techkon-gummitechnik.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://{REQUEST_URI}> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 170, in errorback
    loader.add_value("start_url", "")
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://bytecmed.com/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://metallbaufoerstl.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://validas.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://wittinger-gmbh.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://dekoguenther.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://mekon-recycling.com> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://isys-berlin.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://mg-produktservice.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.abw-verlag.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.gustav-mueller.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://vsp-direktmarketing.de/startseite/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.holzprofi-gerdes.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://petrologic.dmt.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.hans-im-glueck.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.ape-engineering.de/home/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.paul-neuhaus.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://kaiser-waldbrunn.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.sw-greifswald.de/grimmenenergie> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://vaeth.com/index.php?lang=de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.eichsfeldwerke.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://stoehr-logistik.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.engine] INFO: Closing spider (finished)
2018-05-23 11:03:40 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/builtins.ValueError': 1,
 'downloader/exception_type_count/idna.core.IDNAError': 1,
 'downloader/exception_type_count/twisted.internet.error.DNSLookupError': 1,
 'downloader/request_bytes': 13135,
 'downloader/request_count': 45,
 'downloader/request_method_count/GET': 45,
 'downloader/response_bytes': 212477,
 'downloader/response_count': 42,
 'downloader/response_status_count/200': 22,
 'downloader/response_status_count/301': 18,
 'downloader/response_status_count/302': 2,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 23, 9, 3, 40, 845657),
 'log_count/ERROR': 25,
 'log_count/INFO': 7,
 'log_count/WARNING': 1,
 'response_received_count': 22,
 'scheduler/dequeued': 45,
 'scheduler/dequeued/memory': 45,
 'scheduler/enqueued': 45,
 'scheduler/enqueued/memory': 45,
 'spider_exceptions/KeyError': 25,
 'start_time': datetime.datetime(2018, 5, 23, 9, 3, 36, 353661)}
2018-05-23 11:03:40 [scrapy.core.engine] INFO: Spider closed (finished)
