2018-05-23 11:03:37 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: ARGUS)
2018-05-23 11:03:37 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.7, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 17.5.0 (OpenSSL 1.0.2n  7 Dec 2017), cryptography 2.1.4, Platform Windows-7-6.1.7601-SP1
2018-05-23 11:03:37 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'ARGUS', 'CONCURRENT_ITEMS': 200, 'CONCURRENT_REQUESTS': 100, 'COOKIES_ENABLED': False, 'DOWNLOAD_MAXSIZE': 10000000, 'FEED_URI': 'file:///I:/%21Projekte/BMBF_TOBI_131308/01_Arbeitspakete/01_Webscraper/Webscraper/crawler/ARGUS/items/ARGUS/textspider/2a91ee225e6811e891705459596fa410.jl', 'LOG_FILE': 'logs\\ARGUS\\textspider\\2a91ee225e6811e891705459596fa410.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'ARGUS.spiders', 'REACTOR_THREADPOOL_MAXSIZE': 30, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['ARGUS.spiders']}
2018-05-23 11:03:37 [py.warnings] WARNING: c:\programdata\anaconda3\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.feedexport.FeedExporter` class is deprecated, use `scrapy.extensions.feedexport.FeedExporter` instead
  ScrapyDeprecationWarning)

2018-05-23 11:03:37 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-05-23 11:03:37 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-05-23 11:03:37 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-05-23 11:03:37 [scrapy.middleware] INFO: Enabled item pipelines:
['ARGUS.pipelines.TextPipeline']
2018-05-23 11:03:37 [scrapy.core.engine] INFO: Spider opened
2018-05-23 11:03:37 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://greensill-bank.com> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://drg-diagnostics.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://meuser-optik.com/start.html> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://herrmann-bosch.de/slide/index.php> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://weimann-meyer.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.cineplex.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://multiline.cc> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.speditionarndt.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.epn.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://cell-lines-service.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://essinger-landbrot.de> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.taurus-instruments.de/de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.sgb24.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.walter-liehr.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.mattomedia.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.arndt-gruppe.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.ballonreisen.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.epp-germany.com/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.edelrid.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.delker-optik.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.tvg-verlag.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:41 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.realestate.apleona.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:41 [scrapy.core.scraper] ERROR: Spider error processing <GET http://octreopharmsciences.com/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:43 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.phylak.de/> (referer: None)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "I:\!Projekte\BMBF_TOBI_131308\01_Arbeitspakete\01_Webscraper\Webscraper\crawler\ARGUS\ARGUS\spiders\textspider.py", line 188, in parse
    loader.add_value("start_url", response.url)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\loader\__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'start_url'
2018-05-23 11:03:43 [scrapy.core.engine] INFO: Closing spider (finished)
2018-05-23 11:03:43 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 15174,
 'downloader/request_count': 54,
 'downloader/request_method_count/GET': 54,
 'downloader/response_bytes': 467284,
 'downloader/response_count': 54,
 'downloader/response_status_count/200': 24,
 'downloader/response_status_count/301': 26,
 'downloader/response_status_count/302': 4,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 23, 9, 3, 43, 443646),
 'log_count/ERROR': 24,
 'log_count/INFO': 7,
 'log_count/WARNING': 1,
 'response_received_count': 24,
 'scheduler/dequeued': 54,
 'scheduler/dequeued/memory': 54,
 'scheduler/enqueued': 54,
 'scheduler/enqueued/memory': 54,
 'spider_exceptions/KeyError': 24,
 'start_time': datetime.datetime(2018, 5, 23, 9, 3, 37, 257661)}
2018-05-23 11:03:43 [scrapy.core.engine] INFO: Spider closed (finished)
